apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image_send_app
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: image_send_app
  template:
    metadata:
      labels:
        app: image_send_app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sensortype
                operator: In
                values:
                - camera
      containers:
        - name: image_send_app
          image: alicey/image_send_app:latest
          securityContext:
            privileged: true
          env:
            - name: DEVICE_ID
              value: "0"
            - name: POST_URL
              value: "http://127.0.0.1/temp"
            - name: TMP_DIR
              value: "./tmp"            
            - name: INTERVAL
              value: "2"
            - name: INTERVAL_CAPTURE
              value: "5"
              