apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-send-app
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: image-send-app
  template:
    metadata:
      labels:
        app: image-send-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sensortype
                operator: In
                values:
                - camera
      containers:
        - name: image-send-app
          image: alicey/image_send_app:latest
          securityContext:
            privileged: true
          env:
            - name: DEVICE_ID
              value: "0"
            - name: POST_URL
              value: "http://172.10.200.13:32121/api/image/"
            - name: TMP_DIR
              value: "./tmp"            
            - name: INTERVAL
              value: "2"
            - name: INTERVAL_CAPTURE
              value: "5"
              